### ISSUE TITLE
Using pymt5adapter in Linux

### ISSUE THREAD

**Issue by ahmadazizi** [nicholishen/pymt5adapter#1]
Is it possible to use pymt5adapter in Linux?
Right now I am able to run MT5 on Ubuntu linux using Wine, but still no chances with Python. 
The command "wine terminal64.exe" starts the MT5, but I wonder how pymt5adapter would be able to communicate with MT5 executable?

**Comment by nicholishen** [comment]
The limitation is with the MetaTrader5 package from metaquotes. AFAIK, it
will only work in windows.

**Comment by ahmadazizi** [comment]
I just tried to look into the source of that package, its a cpython compiled file. Can you give any clues helping to find out how it connects to exe file?

**Comment by nicholishen** [comment]
It's compiled C with exposed python bindings. You'd have to contact
metaquotes for the source code but I doubt they'd release it...

**Comment by SeamusBoyle** [comment]
@ahmadazizi Install Windows python in the same wine prefix as MT5 along with the MetaTrader5 python package and numpy. It works
