### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by VladPerervenko** [nicholishen/pymt5adapter#4]
After updating 0.3.15 to version 0.4.1, a warning appears.
`> repl_python()
Python 3.6.10 (C:/Users/User/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
Reticulate 1.16 REPL -- A Python interpreter in R.
>>> import pymt5adapter as mt5
ModuleNotFoundError: No module named 'dataclasses'`
Can install the necessary packages along with the update? Not critical

**Comment by nicholishen** [comment]
I forgot that python 3.6 didn't have dataclasses... I changed the Ping dataclass to a namedtuple for the next release. Thanks for bringing that to my attention.

**Comment by metaperl** [comment]
Alternatively, you can make the backport of dataclasses on PyPi a requirement:
pypi.org/project/dataclasses/

But then versions earlier than 3.6 might have issues.
