### ISSUE TITLE
version 3.8.2 not supported?

### ISSUE THREAD

**Issue by VladPerervenko** [nicholishen/pymt5adapter#5]
When updating version 0.3.15 to 0.4.1 (Python 3.8.2) I get a message
`(mlsauce) C:\Users\User>pip install -- upgrade pymt5adapter
ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade`
Is version 3.8.2 not supported?

**Comment by nicholishen** [comment]
3.8.2 is supported. I suspect that there is an issue with the ujson package which I have tagged required in the setup. I'm going to remove that as a requirement in the next release, but highly suggest that if anyone uses logging to install the ujson package.

**Comment by nicholishen** [comment]
> Is version 3.8.2 not supported?

I just remember that there's an issue with older versions of PyCharm and the MetaTrader5 package. The trick is to upgrade pip inside of your virtualenv using 

    (inside virtualenv):easy_install -U pip

**Comment by nicholishen** [comment]
0.4.2 released

**Comment by VladPerervenko** [comment]
Now with version 0.4.3 all my questions are resolved. Good luck
